### PR TITLE
Support for Goaccess

### PR DESCRIPTION
**Pull request by fubarhouse**
PR for #1469, which still needs work.

### CODE REVIEW

**Comment by fubarhouse** [comment]
I've updated the fork to continue work, and it's reaching the point it can work out of the box.

I've replaced the non-working daemon for a cron task run every minute.

The only thing left before you look at it would be a test and slight change for fedora/centos apache log file path or log format configuration. I think Fedora will be the only system affected, but I'll see to it.

**Comment by geerlingguy** [comment]
Thanks! I think what I'd like to do here is create a separate goaccess role, and stash all the OS-specific bits in it. If you're okay with it, I can lift the config you've done here and attribute the initial commit in that new role to you.

**Comment by geerlingguy** [comment]
I'm closing PRs which have conflicts or are failing builds and are older than 6 months old, to tidy up the Drupal VM PR queue; please create a new PR against the latest master branch if you feel this is still an important fix or feature for Drupal VM. Thank you!

**Comment by geerlingguy** [comment]
(Note that I'd still like to switch to GoAccess at some point.)

**Pull request closed without merging**
