### PR TITLE
Add support for custom pre/post ansible tasks.

### PR DESCRIPTION
**Pull request by thom8**
Allow for custom playbook tasks without modifying the playbook.

You can define `custom_pre_tasks_directory` and/or `custom_post_tasks_directory` in your config to a path which will contain custom tasks. 

These are run in alphabetical order.

### CODE REVIEW

**Comment by oxyc** [comment]
I'd definitely prefer this over shell scripts 👍

**Comment by opdavies** [comment]
👍

**Comment by geerlingguy** [comment]
@thom8 - Do you think you could also add a new docs page under 'Other', titled 'Running custom scripts and playbooks' (or something along those lines), with instructions for how someone could do a simple playbook (at least), and pointing to the `examples` directory.

I might also add in a playbook that does the same thing as the existing example Search API Solr configuration...

**Comment by geerlingguy** [comment]
er... just realized we already have `docs/extras/scripts.md` — let's change that page to something that encompasses both shell scripts and playbooks, and get it in.

**Comment by oxyc** [comment]
@thom8 if you're busy I don't mind writing the docs.

But I'm wondering, maybe we should rename these variables to align with `pre_provision_scripts`. Maybe  `pre_provision_tasks_dir` instead (pretty much all role varibles use _dir_). Or maybe just `pre_provision_tasks` as it doesn't necessarily have to be a directory.

**Comment by oxyc** [comment]
Also we need to either define this variable in `example.config.yml` or add `default(omit)`.

**Comment by thom8** [comment]
@oxyc that would be great, if you like we can close this PR and create another with the docs.

We named it `beet_custom_*_tasks` and provide defaults `.beetbox/tasks/pre` & `.beetbox/tasks/post` but not sure if it makes sense in the DVM context.

https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/playbook-provision.yml#L16

**Comment by oxyc** [comment]
#633 but I might just be too tired to write docs at the moment :D

**Comment by thom8** [comment]
Closing for #633

**Pull request closed without merging**
