### PR TITLE
Issue #284: Add docs about vagrant-bindfs

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
Tested it. Before `/var/www/drupalvm` was owned by `501:dialout`. Following the docs they were owned by `vagrant:www-data`.

**Comment by geerlingguy** [comment]
Great, gladly merged in.

**Comment by cdmo** [comment]
Following the instructions in the documentation only works for me after the initial `vagrant up`. Oh and it requires a `vagrant reload` by the way in my experience.

However, every time I try to add it in before the initial `vagrant up` it fails. See below:

```
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Bindfs seems to not be installed on the virtual machine, installing now
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

wget http://bindfs.org/downloads/bindfs-1.13.0.tar.gz -O bindfs.tar.gz

Stdout from the command:



Stderr from the command:

--2016-07-01 17:41:09--  http://bindfs.org/downloads/bindfs-1.13.0.tar.gz
Resolving bindfs.org (bindfs.org)... 127.0.53.53
Connecting to bindfs.org (bindfs.org)|127.0.53.53|:80... failed: Connection refused.
```

Not sure it makes a difference but I'm working with CentOS 7 on the latest version of all software, including DrupalVM.

**Comment by cdmo** [comment]
Guess it might be a coincidence in terms of when I attempt to load bindfs, during a `reload` or the initial `up`. Right now http://bindfs.org/downloads/bindfs-1.13.0.tar.gz is indeed 404ing, [bindfs.org](bindfs.org) is down. Does this site go down intermittently?

**Comment by geerlingguy** [comment]
@cdmo - See upstream issue https://github.com/gael-ian/vagrant-bindfs/issues/46 — I don't use bindfs myself, so I don't know how the long-term reliability has been with it :)

**Comment by gael-ian** [comment]
I confirm its nothing more than a coincidence. bindfs.org has some DNS misconfiguration since Friday but shouldn't be unavailable for long.

**Pull request merged**
