### PR TITLE
Followup #820: Pass ansible arguments via environment variable if provided.

### PR DESCRIPTION
**Pull request by oxyc**
Added docs to @joestewart PR #820. The docs section might not be ideal.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Needs rebase after flurry of other activity.

**Comment by geerlingguy** [comment]
@oxyc - Is this still good to go? Sorry I forgot to take a second look yesterday (things looked good on last review), but I'll merge if you give the 👍

**Comment by oxyc** [comment]
Yup it should be good!

**Comment by oxyc** [comment]
@geerlingguy any other comments on this?

**Comment by geerlingguy** [comment]
Nope, looks good!

**Comment by geerlingguy** [comment]
/me will someday spend some more time doing videos/tutorials on some of these features... just the --start-at-task alone can save a lot of people a lot of time, but little do they know of it's existence :P

**Pull request merged**
