### PR TITLE
Copy Drupal Apache Solr Search conf files into the correct directory.

### PR DESCRIPTION
**Pull request by joestewart**
This should place the files from the Drupal Apache Solr module into the conf directory.

### CODE REVIEW

**Comment by geerlingguy** [comment]
@joestewart - I really, really like this idea, but I don't want to necessarily add it to Drupal VM at this point; a few problems are that this currently only works with the `apachesolr` module, though a significant number of users would like to use `search_api_solr`, and when Drupal 8's Search API Solr module comes around, we'd need to add additional logic to use the D8 copies of the Solr config.

At this time, I think having the process documented separately (docs.drupalvm.com) is good enough, and soon, once #174 is complete, users could add scripts like `post-provision.sh` or `post-provision.yml` that does extra project-specific setup like configuring Solr after the main provisioning is complete.

Thanks!

**Comment by mchelen** [comment]
How about providing this as an option in `config.yml` that is disabled by default? I'm running into the same issue except with `search_api_solr`, and there may be enough users who need some type of Solr integration to make it worthwhile.

**Comment by joestewart** [comment]
I think this use case is the example post provision script - https://github.com/geerlingguy/drupal-vm/blob/master/examples/scripts/configure-solr.sh

**Comment by mchelen** [comment]
@joestewart Ah yeah I see, and it's listed commented out in the `config.yml`. Thanks!

**Comment by geerlingguy** [comment]
Yep! Just added that a week or two ago :)

**Comment by mchelen** [comment]
@geerlingguy Awesome, very handy!

**Pull request closed without merging**
