### PR TITLE
Issue #734: Fix Vagrant 1.8.4 failing to mount NFS synced folders with empty mount_options

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
@geerlingguy could you test this on Vagrant 1.8.1 or have you already upgraded?

**Comment by oxyc** [comment]
Tested and it also works if I set `mount_options: ['vers=3', 'udp']` which is what vagrant does on linux guests.

**Comment by geerlingguy** [comment]
I'm still on 1.8.1 for now, so I'll test there.

**Comment by geerlingguy** [comment]
Worked! I'm going to tag another bugfix release so those using Vagrant 1.8.3+ don't hit this.

**Pull request merged**
