### PR TITLE
Issue #616: Re-enable the XHProf integration test.

### PR DESCRIPTION
**Pull request by geerlingguy**
See: https://github.com/geerlingguy/drupal-vm/issues/616

### CODE REVIEW

**Comment by oxyc** [comment]
The diff I linked to earlier was to the `installed_extras` list where xhprof is disabled :)

**Comment by geerlingguy** [comment]
@oxyc - Umm... yeah, that would do it, wouldn't it :P

**Comment by oxyc** [comment]
This will conflict with https://github.com/geerlingguy/drupal-vm/pull/624/commits/42148c327cd0725b4e9a0d5bb666aa34b0d732e0

**Comment by oxyc** [comment]
Oh I changed the travis logic here. Instead of appending the contents of appending to the default `local.config.yml` I just use a different file if the `local_config` variable is set. So you would have to add the `installed_extras` list to the `ubuntu-16-nginx.config.yml` as well. Felt a bit easier to understand but maybe not.

**Comment by oxyc** [comment]
I did that mostly because I remembered this commit https://github.com/geerlingguy/drupal-vm/commit/3046b6bdaf35d1ca7f6a9214e0e6a2f0b051b76f :)

**Comment by geerlingguy** [comment]
@oxyc - No worries!

**Pull request merged**
