### PR TITLE
Update php-versions role for PHP 7.2 support

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
xdebug doesnt compiled.

> configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.\nconfigure: error: not supported. Need a PHP version >= 5.5.0 and < 7.2.0 (found 7.2.0RC2)

**Comment by oxyc** [comment]
The site install task failed with pretty much the longest stack trail ever. I don't have time to check if it's reproducible tonigt though.

Here's the first few lines:

> TASK [geerlingguy.drupal : Install Drupal with drush.] *************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/var/www/drupalvm/drupal/vendor/drush/drush/drush", "site-install", "standard", "-y", "--root=/var/www/drupalvm/drupal/web", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:01:11.504676", "end": "2017-09-19 03:12:46.967696", "failed": true, "rc": 1, "start": "2017-09-19 03:11:35.463020", "stderr": "Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m\n--notify global option.\nini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nmodule's ini settings at this time DrupalKernel.php:971\nini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nmodule's ini settings at this time DrupalKernel.php:972\nini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nmodule's ini settings at this time DrupalKernel.php:973\nini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nmodule's ini settings at this time DrupalKernel.php:976\nini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nmodule's ini settings at this time DrupalKernel.php:978\nFailed to log error: Deprecated function: assert(): Calling assert() with a string argument is deprecated in Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple() (line 197 of /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Cache/DatabaseBackend.php). #0 /var/www/drupalvm/drupal/web/core/includes/bootstrap.inc(566): _drupal_error_handler_real(8192, 'assert(): Calli...', '/var/www/drupal...', 197, Array)\n#1 [internal function]: _drupal_error_handler(8192, 'assert(): Calli...', '/var/www/drupal...', 197, Array)\n#2 /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Cache/DatabaseBackend.php(197): assert('\\\\Drupal\\\\Compone...', 'Cache Tags must...')\n#3 /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Cache/DatabaseBackend.php(164): Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple(Array)\n#4 /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Cache/DatabaseBackend.php(152): Drupal\\Core\\Cache\\DatabaseBackend->setMultiple(Array)\n#5 /var/www/drupalvm/drupal/web/core/lib/Drupal/Core/Extension/ModuleHandler.php(296)

**Comment by oxyc** [comment]
https://www.drupal.org/node/2853503

**Comment by oxyc** [comment]
Also latest XDebug (2.5.5) doesn't support PHP 7.2 yet.

**Comment by geerlingguy** [comment]
At least merging this in, since it can still be useful for testing (e.g. testing Drupal itself ;), and other things besides Drupal.

**Comment by malikkotob** [comment]
Tried provisioning a new VM with php 7.2 and ran into:

```
TASK [geerlingguy.php-xdebug : Build Xdebug.] **********************************
changed: [blt9] => (item=phpize)
failed: [blt9] (item=./configure) => {"changed": true, "cmd": "./configure", "delta": "0:00:00.559733", "end": "2018-03-22 17:56:17.484875", "item": "./configure", "msg": "non-zero return code", "rc": 1, "start": "2018-03-22 17:56:16.925142", "stderr": "configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.\nconfigure: error: not supported. Need a PHP version >= 5.5.0 and < 7.2.0 (found 7.2.3-1+ubuntu16.04.1+deb.sury.org+1)"
```

Is this what @oxyc was facing above?

**Pull request merged**
