### PR TITLE
Issue #1220: Fix to ensure www-data is in the same group as NFS synced dirs

### PR DESCRIPTION
**Pull request by oxyc**
This is still WIP. Not the nicest solution and it needs proper testing.

Using `stat.gr_name` would be way nicer and could remove the shell task, unfortunately I can't get this to work though. It's never defined in my case.

Also, if the user sets `vagrant_synced_folder_default_type` to something other than `nfs` while using `nfs` for the primary synced folder, this wont help. Other than that I don't see this causing issues. Maybe with smb somehow?

### CODE REVIEW

**Comment by geerlingguy** [comment]
Yeesh, it looks a little fragile (and definitely a bit obtuse), but let me play around when I get some time and see if there's a better way I can think of (probably not... but who knows!).

I'd rather not merge this without considering it a while.

Also, the build failures:

https://travis-ci.org/geerlingguy/drupal-vm/jobs/211519983#L2205 and https://travis-ci.org/geerlingguy/drupal-vm/jobs/211519985 have:

```
/opt/mailhog/mhsendmail: not found
```

Maybe just a fluke? I'll kick those builds again.

**Comment by oxyc** [comment]
I went down the rabbit hole trying to figure out why `stat.gr_name` isn't available for the directory but couldn't find anything. I'll look into it again later as well.

**Comment by oxyc** [comment]
Okay I figured out why gr_name isnt working. In ansible 2.2.0.0 before https://github.com/ansible/ansible-modules-core/commit/52e0536fae2ae8df752f41868ed50486b5653292 `getgrgid` never ran if `getpwuid` failed, which it did because of the nonexisting 501 user.

Unfortunately the commit above isn't in a tagged release yet. Once it is, the shell task can be removed.

**Comment by oxyc** [comment]
Unfortunately the commit isnt in `v2.2.2.0-0.2.rc2` either. But it is in `v2.3.0.0-0.1.rc1`

**Comment by oxyc** [comment]
Also just realized this only fixes the issue for Debian. We need to use the httpd user for centos.

**Comment by oxyc** [comment]
@geerlingguy I pushed a commit so you can see how it will look once Ansible 2.3 is a dependency.

One nice thing about this is I believe it will solve almost all permission related errors people have. Out of the box.

**Comment by oxyc** [comment]
Added a safety check in case the group resolves to root (in case someone somehow runs ansible with sudo). Maybe it's not needed but feels a bit safer...

**Comment by geerlingguy** [comment]
Interesting... it's definitely looking less shaky, and in a quarter or two, once 2.3 has been stable for a while, we could ditch the older tasks. I'll give it a spin.

**Comment by oxyc** [comment]
For rererence, if someone syncs using the default VirtualBox synced folders method, the owner:group will be `vagrant:vagrant`.

As long as the user also changed `vagrant_synced_folder_default_type: ""` www-data will end up being part of the `vagrant` group. If they don't change the default folder type, the group will resolve to dialout on osx. I dont see this scenario happening though.

What's more likely to happen is that a Windows user sets

```yaml
vagrant_synced_folder_default_type: ""
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupalvm
    type: ""
    create: true
```

and thus the owner:group becomes `vagrant:vagrant` with www-data added to the `vagrant` group.

**Comment by geerlingguy** [comment]
Looks good now—we'll just have to remember to drop the Ansible < 2.3 support sometime in the future. Thanks!

Hopefully this will head off the percentage of issues that keep popping up for permissions-related things!

**Comment by nvahalik** [comment]
I just tried this and my NFS mount (using `ubuntu1204`) is still `root:root`. This is on a completely new box.

I'm on Windows 7 and I'm using the `vagrant-winnfsd` plugin.

**Pull request merged**
