### PR TITLE
Support Nginx access logs.

### PR DESCRIPTION
**Pull request by joestewart**

### CODE REVIEW

**Comment by geerlingguy** [comment]
If no access log is defined per server block, it should log using the default config for Nginx, which I think is set to /var/log/nginx/access.log—is that not adequate for most use cases?

**Comment by joestewart** [comment]
I'll try again but wasn't seeing anything written.

**Comment by geerlingguy** [comment]
@joestewart - Note that, by default, Nginx doesn't write logs to disk until a buffer is full; you can simulate a buffer flush by restarting nginx (`sudo service nginx restart`); see if the log is populated after you restart Nginx. If so, buffering is turned on.

**Comment by geerlingguy** [comment]
(See: http://nginx.org/en/docs/http/ngx_http_log_module.html)

**Comment by joestewart** [comment]
Yes, it was the buffering.  I hadn't noticed it until I had added the template change.  

The released version is working well.

BTW, the Nginx and nodejs support in 2.1.0 is great.

**Comment by geerlingguy** [comment]
@joestewart - I do what I can :)

I'll be hopefully getting time to write a few blog posts on Nginx + Drupal in the next month, too; it'll be on Drupal planet!

**Pull request closed without merging**
