### PR TITLE
Followup #608: Automate ansible-galaxy install step

### PR DESCRIPTION
**Pull request by oxyc**
https://github.com/geerlingguy/drupal-vm/issues/608#issuecomment-218793792

### CODE REVIEW

**Comment by oxyc** [comment]
Figured out a way to disable the galaxy step as well. Create a `Vagrantfile.local` with

```rb
config.vm.provisioners[0].config.galaxy_role_file = nil
```

I doubt any regular user will ever re-provision unless they are upgrading Drupal VM. I think it's mostly developers of Drupal VM who might do it and become annoyed by the added time. But by adding this to our `Vagrantfile.local` it wouldn't be an issue for us either.

**Comment by geerlingguy** [comment]
> I doubt any regular user will ever re-provision unless they are upgrading Drupal VM. In which case they do want to re-install the roles. I think it's mostly developers of Drupal VM who might run re-provisions frequently and become annoyed by the added time for provisioning. I believe this hack solves that minor annoyance.

Well... that's true. Hmm. I'm going to think through it and just make sure it won't cause any other weird frustrations that we haven't thought of yet. I like this a lot though. #MakeItMaintainable

**Comment by oxyc** [comment]
So galaxy support was added in 1.8.0 and did have a few bugs but all of them are filed under `provisioners/ansible_local` in the CHANGELOG. So I think that means we're fine.

**Comment by geerlingguy** [comment]
Your other amazing PR has introduced a merge conflict :)

**Comment by geerlingguy** [comment]
Git just can't handle the awesomeness that will be 3.0.0.

**Comment by oxyc** [comment]
Fixed.

**Pull request merged**
