### PR TITLE
Use OverlayFS instead of loopback

### PR DESCRIPTION
**Pull request by oxyc**
Just trying something out #434

Based on http://www.projectatomic.io/blog/2015/06/notes-on-fedora-centos-and-docker-storage-drivers/

### CODE REVIEW

**Comment by oxyc** [comment]
Seems like this wont work anyway:

> RPMs and Yum. OverlayFS only implements a subset of the POSIX standards. This can result in certain OverlayFS operations breaking POSIX standards. One such operation is the copy-up operation. Therefore, using yum inside of a container on a Docker host using the overlay storage driver is unlikely to work without implementing workarounds.
https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

**Comment by geerlingguy** [comment]
:(

**Comment by oxyc** [comment]
Seems it was fixed for CentOS 7 (probably what it's using and why it's fast) but doesnt look like it was backported to CentOS 6. https://bugzilla.redhat.com/show_bug.cgi?id=1213602#c51

The fix seems to be in [`yum-utils-1.1.31-34.el7.src.rpm`](https://rhn.redhat.com/errata/RHBA-2015-2129.html) avaiable for CentOS 7. Latest version for CentOS 6 is `1.1.30`.

Also https://github.com/docker/docker/issues/10180

**Comment by oxyc** [comment]
Okay so this is a dead-end. Overlay isnt even available.

**Comment by oxyc** [comment]
For reference it uses `aufs`.

**Pull request closed without merging**
