### PR TITLE
Add an intro message for vagrant up/reload

### PR DESCRIPTION
**Pull request by oxyc**
Just posting ideas...

```sh
==> drupalvm_project: Mounting NFS shared folders...
==> drupalvm_project: Mounting shared folders...
    drupalvm_project: /var/www/drupalvm => /Users/cindy/Projects/Personal/drupal-vm
==> drupalvm_project: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm_project: flag to force provisioning. Provisioners marked to run always will still run.

==> drupalvm_project: Machine 'drupalvm_project' has a post `vagrant up` message. This is a message
==> drupalvm_project: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm_project:
==> drupalvm_project: Your Drupal VM Vagrant box is ready to use!
==> drupalvm_project: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm-project.dev (or http://192.168.99.88)
==> drupalvm_project: * You can SSH into your machine with `vagrant ssh`.
==> drupalvm_project: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com
```

### CODE REVIEW

**Comment by oxyc** [comment]
My reasoning is that rather than account for all the different scenarios, just make the message useful for beginners and let eg teams who have some fancier setup (disabled dashboard, blabla) either a) disable the message by setting `vagrant_post_up_message: false` or b) set their own welcome message to introduce co-workers to the VM.

**Comment by geerlingguy** [comment]
I like this idea! Does `vagrant_post_up_message: false` actually work, though? It seems like it would cause the else to be triggered...

**Comment by oxyc** [comment]
Oh right! I'll fix that.

**Comment by geerlingguy** [comment]
Works for me!

**Pull request merged**
