### PR TITLE
Issue #1468: Fix various Linux issues with NFS by defaulting to TCP

### LINKED ISSUE #1468: Latest `nfs-utils` doesn't work out of the box with Vagrant
### Issue Type

 - Bug Report / Support Request

### Summary

As of [`nfs-utils-2-1-2-rc2`](http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=commit;h=fbd7623dd8d5e418e7cb369d4026d5368f7c46a6) ([discussion](https://patchwork.kernel.org/patch/9591703/)) UDP is disabled by default thus requiring the user to either:

1.  enable udp in `/etc/nfs.conf`
2. change the nfs options in Drupal VM's `config.yml`

At the moment this only affect Fedora 25+ but we _have had_ issues regarding this before. Not sure what prompted them then as the the repo sources do specify versions that should have udp and nfsv3 support.

Some `nfs-utils` versions across distros.

- [x] Ubuntu 16.04: UDP enabled `nfs-utils v1.2.8` [ref](https://launchpad.net/ubuntu/xenial/+source/nfs-utils)
- [ ] Fedora 25, 26: UDP disabled `nfs-utils v2.1.1-5.rc4+` [ref](https://apps.fedoraproject.org/packages/nfs-utils)
- [x] Arch Linux: UDP enabled `nfs-utils v2.1.1-4` [ref](https://www.archlinux.org/packages/core/i686/nfs-utils/)
- [x] Debian 9: UDP enabled `nfs-utils v 1.3.4-2.1` [ref](https://packages.debian.org/search?searchon=sourcenames&keywords=nfs-utils)

I think it's still fairly safe to default to nfsv4 on Linux hosts as they mention in the commit that it's been supported for a decade. A possible fix:

```rb
   if options[:type] == 'nfs' && !options.key?(:nfs_version) && Vagrant::Util::Platform.linux?
     options[:nfs_version] = 4
     options[:nfs_udp] = false
   end
```

Related:
- https://github.com/geerlingguy/drupal-vm/issues/1040#issuecomment-313215521
- https://github.com/geerlingguy/drupal-vm/issues/245
- https://github.com/geerlingguy/drupal-vm/issues/1425#issuecomment-310796259
- https://github.com/geerlingguy/drupal-vm/issues/1375
- https://github.com/geerlingguy/drupal-vm/issues/893

### PR DESCRIPTION
**Pull request by oxyc**
This needs manual testing to verify if it in fact fixes #1468. Also worth comparing build performance on macOS. I'll run a few builds and post my own results.

### CODE REVIEW

**Comment by oxyc** [comment]
Protocol | `vagrant up` | `vagrant up` | `vagrant provision` | `vagrant provision`
---------|------|------|------|------
TCP | 14m 57.644s | 16m 9.194s | 5m 2.241s | 4m 48.355s
UDP | 15m 4.771s | 16m 10.003s | 4m 55.933s | 4m 32.737s
Native | 13m 21.681s | 13m35.999s | 4m 32.513s | 4m26.933s

_I was still using the computer while the tasks where running so the results are only to check if there's a noticeable difference in overall performance._

---

Here are some more accurate results from running the `composer create-project` manually in different types of shared folders from within the VM:

Protocol | run 1 | run 2 | run 3 | run 4 | run 5
------|-------|-------|-------|-------|-------
UDP | 2m2.865s | 2m9.170 | 2m6.112s | 2m5.399s | 2m7.807s
TCP | 2m0.087s | 2m3.318s | 1m59.806s | 2m0.329s | 2m1.285s
Native | 0m43.414s | 0m41.054s | 0m44.107s | 0m46.235s | 0m45.096s

Script I used after having warmed up the cache:

```sh
for method in tcp udp native; do for i in {1..5}; do echo "$method $i"; time composer create-project drupal-composer/drupal-project:8.x-dev /var/www/$method/$i --stability dev --no-interaction -q; done; done
```

I created the directories on my host machine `udp`, `tcp`, `native` and added this config:

```yaml
vagrant_synced_folders:
  - local_path: ./native
    destination: /var/www/native
    type: rsync
    create: true

  - local_path: ./udp
    destination: /var/www/udp
    type: nfs
    create: true
    options_override:
      nfs_udp: true

  - local_path: ./tcp
    destination: /var/www/tcp
    type: nfs
    create: true
    options_override:
      nfs_udp: false
```

**Comment by geerlingguy** [comment]
Thanks for your work on this; I promise I'll get around to testing soon as well—I've just been completely on a different track this week, so can't context switch yet.

**Comment by oxyc** [comment]
This might be a breaking change for some. Anyone with a firewall who previously whitelisted the udp traffic would need to allow the tcp traffic as well.

**Comment by geerlingguy** [comment]
@oxyc - So the code review looks good / makes sense (and gets rid of some annoying documentation that probably just made the problem worse)—is there anything else required for this, or shall I hit the merge button?

**Comment by oxyc** [comment]
Yeah for some reason I thought NFSv4 was needed for TCP, just me misreading the vagrant docs I think...

To me this is looks good, but as it's still a big switch I'm not 100% confident as there's so many setups out there.. https://github.com/mitchellh/vagrant/issues/7799#issuecomment-315909690 makes me a bit more comfortable at least.

**Comment by geerlingguy** [comment]
Yeah, hopefully the few people it would negatively impact would also be the few who understand at least a little about where the problem lies!

**Pull request merged**
