### PR TITLE
Use drupal_domain for extra vhosts

### PR DESCRIPTION
**Pull request by opdavies**
Use the drupal_domain variable to the extra vhost servernames.

Also, added some extra spaces to make it easier to read. :)

### CODE REVIEW

**Comment by geerlingguy** [comment]
Unfortunately, when we do this, it makes it so the domains aren't added properly via vagrant-hostsupdater... can you think of a simple way to get hostsupdater to work with this style of variable-built subdomains?

**Comment by shawnachieve** [comment]
I just added a PR that allows this to be supported: https://github.com/geerlingguy/drupal-vm/pull/184

**Comment by opdavies** [comment]
@geerlingguy Interesting. I hadn't noticed this before.

@shawnachieve Great. I'll check it out. :)

**Comment by geerlingguy** [comment]
I'm going to move forward with @shawnachieve's PR, and close this one. Thanks for reminding me to keep the variables flexible/consistent, @opdavies !

**Pull request closed without merging**
