### PR TITLE
PR #623: Add support for custom pre/post ansible tasks.

### PR DESCRIPTION
**Pull request by oxyc**
The first sentence is probably the longest in history but not enough sleep to think clearly at the moment.

### CODE REVIEW

**Comment by oxyc** [comment]
Not sure if omit works here, but let's see. Ref https://github.com/ansible/ansible/issues/13296#issuecomment-159768329

**Comment by oxyc** [comment]
@thom8 heads up over at beetbox: https://travis-ci.org/geerlingguy/drupal-vm/jobs/130178132#L1110

**Comment by thom8** [comment]
@oxyc don't think you need to set a default as it skips if the folder is empty or doesn't exist.

**Comment by oxyc** [comment]
Ah just noticed you don't have the `when` clause, and rely on the variable existing. That's what caused the test failure here.

**Comment by thom8** [comment]
The variable need to be set but it can it can point to an empty or non existing directory.
Otherwise, it could be a list of files similar to provisioning scripts.

**Comment by geerlingguy** [comment]
@thom8 / @oxyc - Do we need to add a var to `example.config.yml` for this, or will `default(omit)` work okay? Tests seem to be passing...

**Comment by oxyc** [comment]
Yes this work. I think we still have a few invalid `when` clauses for `with_item` though. Haven't looked properly but at least the cron tasks `when` clause doesnt do anything.

**Comment by geerlingguy** [comment]
Ha, yeah, we can clean those up later. I often overapply the `when`s.

**Pull request merged**
