### PR TITLE
Issue #550: Make unzip a dependency

### PR DESCRIPTION
**Pull request by oxyc**
The package is small and I don't really see a use case for someone not wanting it. What do you think?

### CODE REVIEW

**Comment by geerlingguy** [comment]
Looks good to me.

**Comment by heddn** [comment]
The composer error specifically mentioned zip and unzip. I'm not sure if both are required. I'd have to test.

**Comment by heddn** [comment]
And thanks for such fast turn around time!

**Comment by heddn** [comment]
Yeah, seems unzip is all that is needed for cloning. Now no errors when doing a `composer install --prefer-dist`

**Pull request merged**
