### PR TITLE
Updates to examples and syntax highlighting.

### PR DESCRIPTION
**Pull request by scottreese**
* Updated behat.yml to include the needed contexts to load and use the DrupalExtension driver.
* Updated behat.yml to include region mapping for content region so the DrupalExtension could find it.
* Updated examples to point to features/web since that is what behat.yml is set up for.
* Added syntax to code fences to help fix formatting on the web page.

### CODE REVIEW

**Comment by geerlingguy** [comment]
Looks great to me—much cleaner, thanks!

**Comment by scottreese** [comment]
Still doesn't appear to be rendering properly on this page: http://docs.drupalvm.com/en/latest/extras/behat/ even though it looks fine here on github. :/

**Comment by geerlingguy** [comment]
I remember running into that issue on readthedocs before—can you open up a new issue in the issue queue mentioning this problem (and linking to that page) and I'll commit a few different tests to see how to get it working?

The problem is it's a code block in a list, and every markdown parser treats those differently. I think there might be another example _somewhere_ in the docs.

**Comment by scottreese** [comment]
Ah, yes, I was just coming to that conclusion when you commented. Issue created here: https://github.com/geerlingguy/drupal-vm/issues/280.

**Pull request merged**
