### PR TITLE
Issue #1171: Allow client to pass PHP and XDEBUG environemnt variables over SSH

### PR DESCRIPTION
**Pull request by oxyc**
~todo: docs~

### CODE REVIEW

**Comment by geerlingguy** [comment]
@oxyc - Can you document somewhere how to use this?

**Comment by oxyc** [comment]
I'll try and play around with some examples for this during the weekend but I'm now thinking that maybe it's useful to have this toggled on by a config option instead. It could be useful outside the realm of xdebug and seems odd that it's depending on it.

Maybe add `ssh_accept_php_vars: true`

**Comment by FinBoWa** [comment]
@oxyc just hit me that i commented on the https://github.com/geerlingguy/drupal-vm/issues/716#issuecomment-283272705 and that was closed all ready. 

So wouldn't it be better that ansible generated those lines to the vagrant users bashrc and based them on the config.yaml settings.

**Comment by oxyc** [comment]
I don't think they should be hardcoded to be honest. I feel it's better if especially `PHP_OPTIONS` is set only when required, and not on every CLI request.

**Comment by oxyc** [comment]
I applied for a PhpStorm opensource license, let's see if I get it before the weekend and I can do some testing.

**Comment by oxyc** [comment]
I quickly remembered why I'm still using vim... I have to postpone getting into this whole IDE thing again...

**Comment by geerlingguy** [comment]
@oxyc - You and me both. Getting Xdebug happy through an IDE with PHP reminds me of developing for Java... way overcomplicated just to print out a variable :P

**Comment by FinBoWa** [comment]
For me getting xdebug working with Vim would be problematic also :). Anyways the phpstorms https://www.jetbrains.com/help/phpstorm/2016.3/zero-configuration-debugging.html is quite a breez to configure but the documentation for it is way overly verbose. 

I could translate my guide on getting phpstorm to work somewhat right in 5 steps tomorrow.

**Comment by geerlingguy** [comment]
Is this still necessary/required? I have things working with Sublime Text 3 without needing to set any additional vars like those in the PR... I'm still not entirely clear on why this is required... but I also don't use PHPStorm much.

**Comment by thom8** [comment]
I think this PR is for CLI XDEBUG via SSH.

**Comment by geerlingguy** [comment]
@thom8 - Oh, I was totally misreading that. In that case, does anyone have any objections to the way @oxyc implemented this? I figure we could sneak it into the 4.5.0 release as well.

**Comment by bdone** [comment]
no objections. it would be helpful and appreciated. thanks!

**Comment by geerlingguy** [comment]
I'd like some form of docs (even if it's just inline in a comment on this PR) before merging, though.

**Comment by oxyc** [comment]
I verified that the above examples work (after stumbling around because the ssh service isn't restarted on changes).

**Comment by oxyc** [comment]
Probably better to use `default_enable` in the examples as that's the more likely use case. I just verified that it worked by checking that the `/tmp/cachegrind.out.*` files were generated correctly when using `profiler_enable`.

**Comment by geerlingguy** [comment]
Restarted build, hopefully it comes back all green this time.

**Pull request merged**
