### PR TITLE
Add ability to override drush make command line options.

### PR DESCRIPTION
**Pull request by jayusa123**
I needed to be able to customize the drush make command line options for a project. So, I added the ability to completely override the options used during provisioning. I think others may find it useful as well.

### CODE REVIEW

**Comment by jayusa123** [comment]
Thought I'd just provide an example situation where one might want to override the drush make options. I have created a dev DrushVM repo that pulls down core and our custom installation profile. The profile then pulls in a number of custom modules that we maintain. It is very helpful to run drush make with the `--working-copy` option so that we have usable clones of all the custom modules' repos. This way we can just push the code after making changes to any of our modules.

Thanks!
Jay

**Comment by geerlingguy** [comment]
I'm not necessarily opposed to this addition (I'll merge after poking and prodding it a little), but one note: you can also specify working-copy per-project inside your make file, e.g. https://github.com/geerlingguy/drupal-vm/blob/master/example.drupal.make.yml#L21 (in case you hadn't seen that before; I learned of it a year or so ago and was happy to know I could specify that option in the makefile).

**Comment by jayusa123** [comment]
Hmm, no kidding. I haven't seen that before. Do you know if it applies to all the modules in that case or just core?

**Comment by geerlingguy** [comment]
@jayusa123 - I think all modules.

**Pull request merged**
