### PR TITLE
Add a travis test for Ubuntu 14.04

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
Hmm this is the second time it stalls at https://travis-ci.org/geerlingguy/drupal-vm/jobs/187804211#L1968

No clue as to why

**Comment by geerlingguy** [comment]
Ah... no TTY: https://github.com/geerlingguy/ansible-role-mysql/blob/master/.travis.yml#L38

Means no colored output in Travis, but it's some wacky bug with the MySQL init script, Ansible 2.x, Docker 1.12, and Travis.

**Comment by oxyc** [comment]
Wow, that's probably the wackiest bug I've ever heard of.

**Comment by geerlingguy** [comment]
> Wow, that's probably the wackiest bug I've ever heard of.

Yep, spent like 8 hours on it before giving up. See: https://github.com/ansible/ansible-modules-core/issues/2459#issuecomment-246880847

**Comment by geerlingguy** [comment]
And _of course_ the 14.04 test takes two minutes longer than the rest :)

**Pull request merged**
