### PR TITLE
Issue #649: Add docs on how to use vagrant-lxc

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
Would be nice if we could detect if ufw/ip6tables/etc was actually functioning before calling them. Seems it's always some kernel requirements missing.

**Comment by oxyc** [comment]
I reverted the first commit which defaulted the `drupalvm_disable_ufw_firewall` variable. Maybe not worth it as we have docs anyways...

Thought I'd let you have a say if you prefer defaulting it rebasing it away though.

Also these docs still need some testing.

**Comment by oxyc** [comment]
@geerlingguy could you test these docs at some point when you're using your linux machine? I might just set up my old thinkpad for some testing purposes as well...

**Comment by oxyc** [comment]
Fixed `modprobe` only accepting a single module.

**Comment by oxyc** [comment]
Also there seems to be some sort of race condition going on.

From time to time I get:

> NFS requires a host-only network to be created. Please add a host-only network to the machine (with either DHCP or a static IP) for NFS to work.

If I re-run `vagrant destroy; vagrant up --provider=lxc` it eventually (90% of the time on the second try already) works.

**Comment by geerlingguy** [comment]
@oxyc - I will try to do it this week. Just have to reboot the ol' ThinkPad into Fedora.

**Comment by geerlingguy** [comment]
Still haven't found the time. I even had everything set up last week before a couple prod issues resulted in back-to-back hotfixes and no time :(

**Comment by geerlingguy** [comment]
I think I'll merge the other PR for docs overhaul before incorporating this one. This week I've had a bunch of audio gear sitting on top my PC laptop, so I haven't had the chance to even open it up!

**Comment by geerlingguy** [comment]
@oxyc can you update the PR for the new layout? I'm comfortable merging it in, then anyone who finds issues can open up follow-up tickets.

**Pull request merged**
