### PR TITLE
Issue #1368: Fix private files not accessable with nginx

### PR DESCRIPTION
**Pull request by oxyc**
Just a PR, I haven't tested this. @yobottehg could you verify if this works?

### CODE REVIEW

**Comment by geerlingguy** [comment]
LGTM otherwise. I don't have an install set up locally to test it on, though.

**Comment by oxyc** [comment]
Me neither, if no one else can I can test it during the weekend.

**Comment by yobottehg** [comment]
@oxyc i just tested it with a reprovision and it works. thank you for the PR.

**Comment by geerlingguy** [comment]
Thanks for confirming, @yobottehg!

**Comment by yobottehg** [comment]
Perfect, thanks all!

**Pull request merged**
