### PR TITLE
Fix various alias issues in dashboard, hostsupdater and drush aliases

### PR DESCRIPTION
**Pull request by oxyc**
**Needs manual testing** I'm on an even slower connection today, so wont be able to test it until some other day.

- This fixes: #479
- Simplifies the alias logic in `Vagrantfile`
- Support nginx aliases as well as redirects for hostsupdater/hostsmanager
- Fixes dashboard hosts entry logic never to ignore hosts, only ignore hosts when the entry becomes `192.168.88.88 192.168.88.88` (dashboard).
- Fixes broken drush aliases when nginx aliases are used.

I do not create drush aliases for every host alias intentionally. Only the first one will be used.

### CODE REVIEW

**Comment by geerlingguy** [comment]
I will work on some testing later today. Home projects this weekend, which is why I've been a bit under the radar :)

**Comment by oxyc** [comment]
Thanks, otherwise I can test it on Monday, I'll have time then.

- [ ] Need to verify drush alias file (both local and remote) when using nginx
- [ ] Need to check the hostsupdater aliases are gathered correctly for multiple `server_name` and multiple `server_name_redirect` on nginx
- [ ] Check dashboard

**Comment by oxyc** [comment]
@geerlingguy I tested it and it works in my scenarios with multiple `server_name` as well as multiple `server_name_redirect`. Also fixed a bug where redirects didnt work for multiple hosts in `server_name`.

**Comment by oxyc** [comment]
Just realized we should probably create drush aliases for webserver aliases as well. For multisite. I'll push another commit once I've tested it and verified that it works.

**Comment by geerlingguy** [comment]
@oxyc - Sounds good, home projects ran a bit late today, so I'll just wait for your final changes then merge. This looks great!

**Comment by oxyc** [comment]
Thanks. This should be mergable if travis passes.

**Comment by geerlingguy** [comment]
Aww, now getting:

```
TASK [Configure host machine drush aliases.] ***********************************
fatal: [localhost -> 127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'serveralias'"}
```

Happens on non-nginx configs.

**Comment by oxyc** [comment]
I'm too used to twig!

**Comment by geerlingguy** [comment]
Yeah, Twig and Jinja2 are soooo close in most cases, it's those little things :)

**Comment by geerlingguy** [comment]
Passed. Merged!

**Pull request merged**
