### PR TITLE
Pass ansible arguments via environment variable if provided.

### PR DESCRIPTION
**Pull request by joestewart**
Opened PR for discussion to address #431 

Possible usage to run only post provisioning tasks and scripts as suggested.

`ANSIBLE_ARGS='--tags=post' vagrant provision`

As mentioned in #431 tags would need to be added for this to be useful.

We could restrict the enviroment variable to tags only like 

"ansible.tags = ENV['ANSIBLE_TAGS']"

But the more general argument would allow other flexibility.

### CODE REVIEW

**Comment by geerlingguy** [comment]
I really like this, nice idea! Might think of a different env variable name though, just to avoid any potential namespace collisions. Maybe `DRUPALVM_ANSIBLE_ARGS`?

**Comment by joestewart** [comment]
Updated to use DRUPALVM_ANSIBLE_ARGS.  It's not going to be a short command line anyway so this seems good.

**Comment by geerlingguy** [comment]
If the env variable is not set, does this cause any issues/warnings?

**Comment by joestewart** [comment]
I haven't seen any difference when the variable isn't set.  Including warnings.

**Comment by oxyc** [comment]
Other useful flags:

- `--vault-password-file ~/.vault_pass.txt`
- `--start-at-task=Run configured post-provision ansible task files.` _due to how vagrant passes the arguments you can't use quotes here._
- `--list-tasks` would be useful for debugging

**Comment by geerlingguy** [comment]
@oxyc - Would you like to take a crack at adding one or more of those and build on top of this PR?

**Comment by oxyc** [comment]
With the current PR it already works.

```
DRUPALVM_ANSIBLE_ARGS='--start-at-task=Run configured post-provision ansible task files.' vagrant provision
```

**Comment by geerlingguy** [comment]
@oxyc - Ah... obvious in hindsight.

Could we add a note in the docs about this new option, and some suggested uses?

**Comment by oxyc** [comment]
Sure.

One minor issue with this is that it only supports a single argument. Vagrant requires the arguments to be passed as an array if there are more than one. This is also why I'm not using quotes in my `--start-at-task` example. I guess we can just add a note on that.

**Comment by geerlingguy** [comment]
Sounds good.

**Comment by geerlingguy** [comment]
Closing for #992 — see progress there.

**Pull request closed without merging**
