### PR TITLE
1579 cableconnect with provisioning

### PR DESCRIPTION
**Pull request by rpsu**

### CODE REVIEW

**Comment by rpsu** [comment]
More info on this over here: @see https://github.com/hashicorp/vagrant/issues/8157#issuecomment-304492943

**Comment by oxyc** [comment]
Would you mind summarizing the issue and how this fixes it? Some steps to reproduce an issue would be great.

**Comment by geerlingguy** [comment]
@rpsu - Same comment as oxyc—I haven't seen this issue crop up on any of my builds; is there an open issue related, or do you have any more details as to what problem you were having that this fixed? Also, would need to know version and OS details to reproduce the issue.

**Comment by geerlingguy** [comment]
Closing this for now—please let us know if you can find a way to reproduce the issue or have a better description of why this change would be helpful to the project.

**Pull request closed without merging**
