### PR TITLE
Make docs about basic setup more understandable

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
I avoided variables to make it more understandable for beginners. The ProxyPassMatch parameter line looks pretty scary to someone unaccustomed to PHP FPM configurations.

**Comment by oxyc** [comment]
Heads up, more commits incoming

**Comment by oxyc** [comment]
Docs are not my strong suit, but I think this gives the reader a bit more information and background to how things work.

**Comment by geerlingguy** [comment]
Looks good to me.

**Pull request merged**
