### PR TITLE
Issue #616: Switch travis tests from Ubuntu 14.04 to 16.04

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by oxyc** [comment]
More use cases for `local.config.yml` :)

**Comment by oxyc** [comment]
Regarding AppArmor being annoying https://github.com/geerlingguy/drupal-vm/pull/456

**Comment by oxyc** [comment]
Just hacking it to see if travis passes. I think this should still pass on a real system, but not sure. If I recall `update.rc-d` doesn't work in docker containers.

**Comment by oxyc** [comment]
Hmpf didnt work to hack it either. Any ideas? I can have another look later today as well.

**Comment by oxyc** [comment]
Yey

**Comment by oxyc** [comment]
Verified that the apparmor task do run when installed locally.

**Comment by geerlingguy** [comment]
Awesome. Thank you SO much for fixing this up!

**Pull request merged**
