### PR TITLE
Issue #1093: Install Apache 2.4.9+ on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by oxyc**

### CODE REVIEW

**Comment by geerlingguy** [comment]
I thought we had an ubuntu1404 test running in Docker through Travis... maybe we need to add one back in—it looks like we're only testing 1604 and centos7. A lot of devs are still on 14.04 :(

**Comment by oxyc** [comment]
Hmm 14.04 is failing on MySQL role https://travis-ci.org/geerlingguy/drupal-vm/jobs/187783415#L976

**Comment by geerlingguy** [comment]
Hmm maybe so... but just needs: https://github.com/geerlingguy/ansible-role-mysql/blob/master/tests/test.yml I think.

**Comment by geerlingguy** [comment]
@oxyc - I won't have time to add in a 14.04 test today, but I'll tag the new release so we get 4.1.x working again for 14.04 users.

**Pull request merged**
