### PR TITLE
Break all the things!

### PR DESCRIPTION
**Pull request by geerlingguy**
See #609

### CODE REVIEW

**Comment by geerlingguy** [comment]
@oxyc - It looks like CentOS 7 isn't happy with all my changes to XHProf... I'm heading to dinner + DrupalCon Trivia Night, and I hate to ask—but if you get a chance, can you spin up an instance running CentOS and test, or even debug it quick via Travis? Otherwise I'll get into it tomorrow.

**Comment by oxyc** [comment]
Installation works but some weird things going on

> Warning: fopen(/var/tmp/xhprof/57354c733f599.xhprof_testing.xhprof): failed to open stream: No such file or directory in XHProfRuns_Default->save_run() (line 135 of /usr/share/php/xhprof_lib/utils/xhprof_runs.php).

Directory exists and is writable but PHP can't write to. Nor can I write to `/var/tmp/` or `/tmp/`. Status report looks okay. Something obvious i'm missing?

**Comment by oxyc** [comment]
Okay so whenever PHP is writing to `/var/tmp` it's actually writing to `/var/tmp/systemd-private-5e8ae5a183394a28b271b174b64e2fe2-php-fpm.service-e5Ml8f/tmp/` where the `xhprof` directory doesn't exist. What RHEL madness is this? :D

**Comment by geerlingguy** [comment]
@oxyc apparently it's a systemd thing... looking into it in the morning.

**Comment by oxyc** [comment]
One way to get around this in Drupal VM is to configure the `output_dir` to just `/var/tmp`. XHProf UI filters for files ending with `.xhprof` anyway. https://github.com/phacility/xhprof/blob/0bbf2a2ac34f495e42aa852293fe0ed821659047/xhprof_lib/utils/xhprof_runs.php#L151

**Comment by oxyc** [comment]
I already set up an instance for debugging locally but seems `xhprof` is just commented out in `example.config.yml`

**Comment by geerlingguy** [comment]
@oxyc - I'm working on this at the DrupalCon sprints. I actually have some bandwidth today (Internet was iffy rest of the week), so I'm making some progress. Trying to get tests to pass before merging.

**Comment by geerlingguy** [comment]
@oxyc - D'oh, diff doesn't show anymore :(

**Pull request merged**
