### PR TITLE
Fixes #203: Only use Ondrej repo for Ubuntu 12.04 when installing 5.5.

### LINKED ISSUE #203: Weird issue "Unmet dependency with apache2-mpm-prefork" expecting trusty5, but using trusty1
Downloaded drupalvm to a new Macbook. Upon vagrant up, I kept getting an error about a version mismatch in the apache2 version being installed and the one it is told to use. I have only changed the VM memory limit in the config.yml. I also deleted the machine and tried from scratch, this error is hit consistently. Vagrant 1.7.4, VirtualBox 4.30.x

### PR DESCRIPTION
**Pull request by geerlingguy**
See: #203

### CODE REVIEW

**Comment by kevinquillen** [comment]
Does this mean if we change the PHP version to 5.6, it will get around this issue temporarily?

**Comment by geerlingguy** [comment]
@kevinquillen - Possibly. Could you try that and see what happens? I would, but I happen to be in another city with very weak internet, so even reloading/reprovisioning a VM locally would take a couple hours :(

**Comment by zrpnr** [comment]
@kevinquillen changing to 5.6 gives the same error, this patch only fixes #203 when using `php_version: "5.5"`

**Comment by geerlingguy** [comment]
@zrpnr - Yep, I forgot that I changed the default to 5.6. I'll work on a better fix.

**Pull request closed without merging**
