### PR TITLE
Issue #455: Add docs on environment specific configs

### PR DESCRIPTION
**Pull request by oxyc**
A first draft of the functionality.

### CODE REVIEW

**Comment by oxyc** [comment]
I avoided giving specific suggestions as I'm not entirely sure what workflow we should be recommending.

Personally I would not entirely trust the environment variable and would instead have the security hardening configurations in `config.yml` while I override them with development tools in `vagrant.config.yml`. This way a production environment will never be provisioned with development tools even if I make a typo in the command.

**Comment by geerlingguy** [comment]
That's... a good point. Do we want to update the docs and recommend cloning `default.config.yml` to `vagrant.config.yml` instead of `config.yml`? Then in the docs we can say "if you consider using Drupal VM for production, you should set the secure overrides in `config.yml` and customize your local environment using `vagrant.config.yml` and production-specific overrides in `prod.config.yml`... something along those lines?

**Comment by oxyc** [comment]
> Do we want to update the docs and recommend cloning default.config.yml to vagrant.config.yml instead of config.yml

You mean in README, all docs, etc?

**Comment by geerlingguy** [comment]
@oxyc - Yeah, maybe... though it might be a bit heavy handed. If Drupal VM becomes used more for multiple environment configuration (e.g. prod, stage, local), then using config this way is a little more correct.

But for the majority use case, currently just mentioning `config.yml` seems to be the simplest/least confusing. So I guess I just convinced myself to _not_ recommend changing things up right now :D

**Comment by geerlingguy** [comment]
@oxyc - Can you also update the README in the prod directory to point to the docs page instead of having duplicated info? Just have the note about 'security is your responsibility', then direct people to the docs URL for more information.

**Comment by oxyc** [comment]
@geerlingguy you want me to move over all the docs from the README?

**Comment by geerlingguy** [comment]
Yeah.

**Comment by geerlingguy** [comment]
This is fine for now... we can iterate on it later :)

**Pull request merged**
