### PR TITLE
Allow for extra YAML config files to be loaded

### PR DESCRIPTION
**Pull request by oxyc**
The ansible tasks aren't as clean as I would like, but I couldn't come up with anything else.

This would support things like:

```
extra_config_files:
  - local.config.yml
  - configs/*.yml
  - configs/php/php56.yml
  - ../vendor/company/drupalvm-configs/varnish.yml
```

Thoughts?

### CODE REVIEW

**Comment by oxyc** [comment]
With Ansible 2.2 something like this would also work:

```yaml
- name: Include extra config files.
   include_vars:
     dir: "{{ config_dir }}"
     files_matching: "{{ item }}"
     depth: 1
     with_flattened:
       - "{{ extra_config_files }}"
       - "{{ lookup('env', 'DRUPALVM_ENV')|default(drupalvm_env, true)|default(ansible_env.DRUPALVM_ENV)|default(omit) }}.config.yml"
```

`files_matching` is actually a regex and not a glob. I can't even figure out how to match things... A simpler way that removes globbing possibilty is:

```yaml
- name: Include extra config files.
   include_vars:
     file: "{{ config_dir }}/{{ item }}"
     with_flattened:
       - config.yml
       - "{{ extra_config_files }}"
       - "{{ lookup('env', 'DRUPALVM_ENV')|default(drupalvm_env, true)|default(ansible_env.DRUPALVM_ENV)|default(omit) }}.config.yml"
```

**Comment by oxyc** [comment]
Something worth mentioning with the 2.2 solutions is that you cannot override `extra_config_files` as they are included one by one, not evaluated in advanced. Ie you cant remove `local.config.yml`.

**Comment by geerlingguy** [comment]
Hmm... it just seems like we're starting to get too far into the territory of _too_ much power being exposed. With a few predefined files, it's more obvious that there's a hierarchy, like:

```
default.config.yml
config.yml
local.config.yml
```

But maybe it's just because that's what I'm used to. I'd like to hear from anyone else—does the current structure end up getting in the way often enough that adding in this functionality (and additional code complexity) help? Basically, for others—would this be worth it?

For _myself_, I haven't felt any pain whatsoever after we added the ability for optional config, and then optional local.config on top of that...

**Comment by oxyc** [comment]
Possible. My primary use case is having a company specific composer dev-dependency with shared drupal-vm config files. So that I can just do a `composer update` rather than editing a dozen repos.

**Comment by oxyc** [comment]
The solution isn't as nice as I would have wanted, and there doesn't seem to be anyone requesting these sort of features except me :) I'll make do with a post-update script keeping configs up to date.

**Comment by geerlingguy** [comment]
@oxyc - No problem, it's not something I'm going to put a blanket 'no' on... but it's something I want to see more than one person request before I add it (since it does add to the already-slightly-more-complex-than-I-like level complexity surrounding where variables come from).

**Pull request closed without merging**
