### PR TITLE
Use composer project based site build as the default

### PR DESCRIPTION
**Pull request by oxyc**
@geerlingguy would you mind testing this to see how the performance has improved since https://github.com/geerlingguy/drupal-vm/pull/694#issuecomment-223688740?

### CODE REVIEW

**Comment by oxyc** [comment]
If this turns out to be fast enough, should we use `build_composer_project` as the default so we can remove a bunch of steps from the quick start guide. Or should we just use `build_composer` and change everything to reference the `example.drupal.composer.json` instead of `example.drupal.make.yml`?

**Comment by geerlingguy** [comment]
Yes! If the performance is close, let's use the simplest setup method.

**Comment by geerlingguy** [comment]
I'll try to run tests tonight, it's crepe night, so it'll have to wait a bit.

**Comment by geerlingguy** [comment]
|| Test type || Time |
| ----- | ----- |
| Makefile default config | 00:06:01 |
| Composer (this PR) | TODO |

**Comment by geerlingguy** [comment]
Testing is good, I'm going to include a default cachier config for #702 once I get a little more testing completed.

**Pull request merged**
